[project]
name = "mvc"
version = "2025.0.0"
dynamic = ["version"]
dependencies = ["fastapi",
    "pydantic",
    "psycopg",
    "yoyo-migrations",
    "python-dotenv"
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
[tool.hatch.envs.default.scripts]
start = "python main.py"
