[project]
name = "mvc"
version = "2025.0.0"
dependencies = [
    "fastapi[standard]",
    "pydantic",
    "psycopg",
    "yoyo-migrations",
    "python-dotenv",
    "datetime"
]

[tool.hatch.envs.default.scripts]
start = "fastapi dev main.py"